### ISSUE TITLE
[Bug]: can't configure a new account `error: Config File "config" Not Found in "[]"`

### ISSUE THREAD

**Issue by thomas-chauvet** [exoscale/cli#548]
### Current Behavior

When I use `exo config` to add a new account, at the end I obtain an error `error: Config File "config" Not Found in "[]"`.

Note: when I use `exo config list`, my account is named `<environment variables>`... However, in `$HOME/Library/Application\ Support/exoscale/exocale.toml` I have:

```toml
defaultaccount = "cli"

[[accounts]]
  account = "XXX"
  defaultZone = "ch-gva-2"
  endpoint = "https://api.exoscale.com/v1"
  key = "XXX"
  name = "cli"
  secret = "XXX"
```

### Expected Behavior

The account should ne added without issue.

### Steps To Reproduce

1. On MacOS Ventura 13.4.1
2. With exoscale-cli installed with brew. Exoscale version `exo 1.74.0 74dd3a35 (egoscale 0.101.0)`
3. `exo config`:
4. ✔ <Configure a new account>
[+] API Key [none]: XXX
[+] Secret Key [none]: XXX
[+] Account name [none]: myaccountname
[+] Name [none]: myname

### CLI Version

1.74.0

### Os platform

MacOS ventura

### Relevant log output

```shell
error: Config File "config" Not Found in "[]"
```
