### ISSUE TITLE
[Bug]: exo dns does not work anymore

### ISSUE THREAD

**Issue by dieti80** [exoscale/cli#716]
### Current Behavior

I have a Cronjob using the exoscale cli to update my DNS records.
For this purpose I created an IAM role with the following rules:
- operation in ['update-dns-domain-record'] && resources.dns_domain_record.type == 'A'
- operation in ['list-dns-domains', 'get-dns-domain', 'list-dns-domain-records', 'get-dns-domain-record']

The API Key to run the commands has the mentioned IAM role applied.

Running any `/exo dns *` commands with the exo cli 1.84.1 works.

docker.io/exoscale/cli:1.84.1
```
/exo dns list
┼──────────────────────────────────────┼───────────┼
│                  ID                  │   NAME    │
┼──────────────────────────────────────┼───────────┼
│ <MY-ID> │ <MY-DOMAIN> │
┼──────────────────────────────────────┼───────────┼
```

Running any `/exo dns *` commands with the exo cli 1.85.0 fails.
docker.io/exoscale/cli:1.85.0
```
 /exo dns list
error: switch client zone v3: get zone api endpoint: list zones: ListZones: http response: Forbidden: Forbidden by role policy for compute
```

Everything is identical besides the CLI version.

I assume this has something to do with #683 

### Expected Behavior

`/exo dns *` commands work with 1.85.0 like it was with 1.84.1

### Steps To Reproduce

1. Create an IAM role in Exoscale with the following rules:
- operation in ['update-dns-domain-record'] && resources.dns_domain_record.type == 'A'
- operation in ['list-dns-domains', 'get-dns-domain', 'list-dns-domain-records', 'get-dns-domain-record']
2. Create an API Key and apply the IAM role to it
3. Start the Exoscale CLI as Pod:
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: exo-cli
spec:
  containers:
    - name: exoscale-cli
      image: docker.io/exoscale/cli:1.85.0
      command: [ "/bin/sh" ]
      args: [ "-c", "tail -f /dev/null" ]
EOF
```
4. Enter into the Pod
```kubectl exec -it exo-cli -- sh```
5. Create a Excoscale config file under /root/.config/exoscale/exoscale.toml 
```
defaultaccount = 'my-account'

[[accounts]]
defaultZone = 'ch-dk-2'
key = '....' <-- Configure the API Key
name = 'my-account'
secret = '...' <-- Configure the secret of the API Key
```
6. Run the `exo dns *` commands

### CLI Version

1.85.0

### Os platform

K3s

### Relevant log output

```shell
error: switch client zone v3: get zone api endpoint: list zones: ListZones: http response: Forbidden: Forbidden by role policy for compute
```
